### ISSUE TITLE
Keep getting "internal server error"

### ISSUE THREAD

**Issue by jjtny1** [GemHQ/round-py#5]
I was following the get started guide and at first everything was working fine. But now every time i call accounts.transactions() or try to make a payment i get this error:

account.transactions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/round/accounts.py", line 161, in transactions
    return txs.Transactions(transaction_resource, self.client)
  File "/Library/Python/2.7/site-packages/round/transactions.py", line 15, in __init__
    super(Transactions, self).__init__(resource, client)
  File "/Library/Python/2.7/site-packages/round/wrappers.py", line 128, in __init__
    self.populate()
  File "/Library/Python/2.7/site-packages/round/wrappers.py", line 141, in populate
    resources = self.resource.list()
  File "/Library/Python/2.7/site-packages/patchboard/resource.py", line 97, in action_fn
    return action.request(self, self.url, *args)
  File "/Library/Python/2.7/site-packages/patchboard/action.py", line 62, in request
    raise ResponseError(response, err_msg)
patchboard.response.ResponseError: Unexpected response status: 500 - {"message":"internal server error","reason":""}

I tried account.refresh(), wallet.refresh(), user.refresh() etc and still same error

**Comment by thedoctor** [comment]
Hey, this is a small server side issue. There's already a fix, but it hasn't been deployed. You can work around the issue in the meantime by making your transactions call with a filter to prevent the problematic transactions (which are stuck in an `unfunded` state that raises an error when being marshaled for response), as such:

    account.transactions(status=['unsigned', 'unapproved', 'unconfirmed', 'confirmed'])

If you shoot an email over to support@gem.co we'll add you to our client slack channel and you can get a quicker response on questions and service problems.

**Comment by jjtny1** [comment]
Thanks,

Ill shoot an email over.
